### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by pranavpatne**

### CODE REVIEW

**Comment by Anubhav-Goyal01** [comment]
Please add the dataset as well @pranavpatne

**Comment by Anubhav-Goyal01** [comment]
@pranavpatne  Please add the dataset in the data column and combine the 2 Jupyter notebooks into one

**Comment by pranavpatne** [comment]
Done with the changes.

**Comment by Anubhav-Goyal01** [comment]
The data folder already exists in the repo @pranavpatne, you don't have to create a new one, add the dataset in that folder and have 1 jupyter notebook, that's it. Only make 2 file changes, you have 4 currently

**Pull request closed without merging**
