### PR TITLE
Common Reusable snippets

### PR DESCRIPTION
**Pull request by YuvrajRakheja**
Common reusable snippets.Added more

### CODE REVIEW

**Comment by YuvrajRakheja** [comment]
Please merge pr @Anubhav-Goyal01

**Comment by Anubhav-Goyal01** [comment]
Please remove the .ipynb and the file without any extension @YuvrajRakheja, I will merger your .py file

**Review by YuvrajRakheja — COMMENTED** [review]
Done @Anubhav-Goyal01

**Comment by YuvrajRakheja** [comment]
Please merge. @Anubhav-Goyal01

**Comment by Anubhav-Goyal01** [comment]
Done @YuvrajRakheja

**Pull request merged**
