### PR TITLE
Add RPS (Rock Paper Scissors) Model

### PR DESCRIPTION
**Pull request by anandha24**

### CODE REVIEW

**Comment by anandha24** [comment]
Hello, please would you merge my pull request? I have contribute to add CNN model to detect RPS and RNN model to detect hate speech in twitter?

**Comment by Anubhav-Goyal01** [comment]
Hello @anandha24, the notebooks which you have written are not completely in English, so it will be difficult for other people to contribute to them, change them to English if you can please, I will merge it in that case

**Comment by anandha24** [comment]
Ok i will modify it

**Comment by anandha24** [comment]
Hello i have update it, can u merge it?

**Comment by Anubhav-Goyal01** [comment]
Please modify the Hate speech notebook as well @anandha24, other 2 notebooks are Ok

**Comment by anandha24** [comment]
Okay @Anubhav-Goyal01 i have updated in last commit, wait i will push it

**Comment by anandha24** [comment]
i have finish my project, please assign hacktoberfest label to me, thank you ^_^

**Pull request merged**
